apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "fbcore.fullname" . }}
  labels:
    {{- include "fbcore.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "fbcore.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  podTargetLabels:
    - app.kubernetes.io/name
    - app.kubernetes.io/namespace
