---
kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "fbcore.fullname" . }}-svc
  labels:
    {{- include "fbcore.labels" . | nindent 4 }}
    firebolt/nodes-count: {{ .Values.nodesCount | quote }}
spec:
  type: ClusterIP
  # create a headless service
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "fbcore.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-query
      port: 3473
      protocol: TCP
    - name: health
      port: 8122
      protocol: TCP
    - name: execp
      port: 5678
      protocol: TCP
    - name: datacp
      port: 16000
      protocol: TCP
    - name: storage-manager
      port: 1717
      protocol: TCP
    - name: storage-agent
      port: 3434
      protocol: TCP
    - name: metadata
      port: 6500
      protocol: TCP
    - name: metrics
      port: 9090
      protocol: TCP
