---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "fbcore.fullname" . }}
  labels:
    {{- include "fbcore.labels" . | nindent 4 }}
    firebolt/nodes-count: {{ .Values.nodesCount | quote }}
spec:
  serviceName: {{ include "fbcore.fullname" . }}-svc
  replicas: {{ .Values.nodesCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "fbcore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fbcore.labels" . | nindent 8 }}
        {{- with $.Values.extra_pod_labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ $.Values.deployment.terminationGracePeriodSeconds }}
      containers:
        - name: core
          image: {{ $.Values.image.repository }}:{{  default $.Chart.AppVersion $.Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODES_COUNT
              value: {{ .Values.nodesCount | quote }}
          command: ["/bin/sh", "-c"]
          tty: true
          stdin: true
          args:
            - |
              export POD_INDEX="$(echo $POD_NAME | awk -F'-' '{print $NF}')"

              exec /firebolt-core/firebolt-core --node $POD_INDEX
          ports:
            - name: http-query
              containerPort: 3473
              protocol: TCP
            - name: health
              containerPort: 8122
              protocol: TCP
            - name: execp
              containerPort: 5678
              protocol: TCP
            - name: datacp
              containerPort: 16000
              protocol: TCP
            - name: storage-manager
              containerPort: 1717
              protocol: TCP
            - name: storage-agent
              containerPort: 3434
              protocol: TCP
            - name: metadata
              containerPort: 6500
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /health/live
              port: 8122
          {{- if .Values.readiness }}
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /health/ready
              port: 8122
          {{- end }}
          resources:
              {{- toYaml $.Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: firebolt-core-data
              mountPath: /firebolt-core/volume
            - name: nodes-config
              mountPath: /firebolt-core/config.json
              subPath: config.json
              readOnly: true
          securityContext:
            {{- toYaml $.Values.deployment.securityContext | nindent 12 }}
            capabilities:
              add:
                {{- toYaml $.Values.deployment.securityCapabilities.add | nindent 16 }}
              drop:
                - ALL
      volumes:
        - name: nodes-config
          configMap:
            name: {{ include "fbcore.fullname" . }}-nodes-config
            items:
              - key: config.json
                path: config.json
  volumeClaimTemplates:
    - metadata:
        name: firebolt-core-data
      spec:
        {{- toYaml $.Values.deployment.storageSpec | nindent 8 }}
