---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "fbcore.fullname" . }}
  labels:
    {{- include "fbcore.labels" . | nindent 4 }}
    firebolt/nodes-count: {{ .Values.nodesCount | quote }}
spec:
  serviceName: {{ include "fbcore.fullname" . }}-svc
  replicas: {{ .Values.nodesCount }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "fbcore.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fbcore.labels" . | nindent 8 }}
        {{- with $.Values.extra_pod_labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ $.Values.deployment.terminationGracePeriodSeconds }}
      {{- if .Values.nonRoot }}
      securityContext:
        fsGroup: 1111
      {{- end }}
      {{- if and .Values.memlockSetup .Values.nonRoot }}
      shareProcessNamespace: true
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: core
          image: {{ $.Values.image.repository }}:{{  default $.Chart.AppVersion $.Values.image.tag }}
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: NODES_COUNT
              value: {{ .Values.nodesCount | quote }}
          command: ["/bin/bash", "-c"]
          tty: true
          stdin: true
          args:
            - |
              REQUIRED_MEMLOCK_BYTES=8589934592 # 8GB
              function get_memlock_limit() {
                cat /proc/self/limits | grep -F 'Max locked memory' | awk '{print $4}'
              }

              echo -n "[Setup] Firebolt Core version "
              /firebolt-core/firebolt-core --version

              {{- if .Values.nonRoot }}
              if [[ $(id -u) -eq 0 ]]; then
                echo "[Setup] Core container is running as root, however deployment used nonRoot=false" 1>&2
                exit 4
              fi

              {{- if .Values.memlockSetup }}
              echo "[Setup] Core entrypoint PID: $BASHPID"
              rm -f /firebolt-core/volume/entrypoint-*.pid
              PID_FILE="/firebolt-core/volume/entrypoint-$POD_UID.pid"
              echo "$BASHPID" > "$PID_FILE"
              trap "rm -f $PID_FILE" EXIT

              ## wait until memlock limits are changed by the helper container
              CURRENT_MEMLOCK_VALUE=$(get_memlock_limit)
              echo "[Setup] current soft memlock limit: $CURRENT_MEMLOCK_VALUE (will wait for limits to be upgraded if below 8GB)" 1>&2
              while true; do
                CURRENT_MEMLOCK_VALUE=$(get_memlock_limit)

                if [ "$CURRENT_MEMLOCK_VALUE" = "unlimited" ]; then
                  break
                fi
                if [ "$CURRENT_MEMLOCK_VALUE" -ge "$REQUIRED_MEMLOCK_BYTES" ]; then
                  break
                fi

                sleep 0.2
              done
              {{- end }}
              {{- else }}
              if [[ $(id -u) -ne 0 ]]; then
                echo "[Setup] Core container is not running as root, however deployment used nonRoot=true" 1>&2
                exit 4
              fi

              {{- if .Values.memlockSetup }}
              echo "WARNING: memlockSetup=true is unnecessary with nonRoot=false" 1>&2
              {{- end }}

              {{- end }}
              echo "[Setup] current memlock limit:" 1>&2
              cat /proc/self/limits | grep -F 'Max locked memory' 1>&2

              rm -f "$PID_FILE"

              export POD_INDEX="$(echo $POD_NAME | awk -F'-' '{print $NF}')"
              exec /firebolt-core/firebolt-core --node $POD_INDEX
          ports:
            - name: http-query
              containerPort: 3473
              protocol: TCP
            - name: health
              containerPort: 8122
              protocol: TCP
            - name: execp
              containerPort: 5678
              protocol: TCP
            - name: datacp
              containerPort: 16000
              protocol: TCP
            - name: storage-manager
              containerPort: 1717
              protocol: TCP
            - name: storage-agent
              containerPort: 3434
              protocol: TCP
            - name: metadata
              containerPort: 6500
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /health/live
              port: 8122
          {{- if .Values.readiness }}
          readinessProbe:
            periodSeconds: 5
            timeoutSeconds: 3
            httpGet:
              path: /health/ready
              port: 8122
          {{- end }}
          resources:
              {{- toYaml $.Values.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: firebolt-core-data{{ if .Values.nonRoot }}-nr{{ end }}
              mountPath: /firebolt-core/volume
            - name: nodes-config
              mountPath: /firebolt-core/config.json
              subPath: config.json
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: false
            {{- if .Values.nonRoot }}
            runAsNonRoot: true
            runAsUser: 1111
            runAsGroup: 1111
            {{- end }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        {{- if and .Values.memlockSetup .Values.nonRoot }}
        - name: memlock-setup
          # use an image which has 'prlimit'
          image: debian:stable-slim
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 64Mi
          securityContext:
            runAsUser: 0
            capabilities:
              drop:
                - ALL
              add:
                - SYS_RESOURCE
          env:
            - name: POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          command: ["/bin/bash", "-c"]
          args:
          - |
            PID_FILE="/firebolt-core/volume/entrypoint-$POD_UID.pid"
            CORE_PID=""

            function wait_for_core_pid() {
              local DELAY="$1"
              echo "[Setup] waiting for Core entrypoint PID" 1>&2
              while sleep $DELAY; do
                if [ ! -f "$PID_FILE" ]; then
                  # file not yet created by main container
                  echo -n .
                  continue
                fi
                # PID file can disappear any moment
                if ! PID_MT=$(stat -c %Y "$PID_FILE"); then
                  echo "[Setup] file deleted by main container while attempting stat" 1>&2
                  continue
                fi
                NOW=$(date +%s)
                AGE=$[NOW - PID_MT]
                if [ $AGE -gt 60 ]; then
                  echo "[Setup] Core PID is $CORE_PID, but it it is older than 1 minute, ignoring until Core container rewrites it" 1>&2
                  continue
                fi
                if ! CORE_PID="$(< $PID_FILE)"; then
                  echo "[Setup] file deleted by main container while attempting read" 1>&2
                  continue
                fi
                if [ -z "$CORE_PID" ]; then
                  echo "[Setup] partial write results in reading of an empty file" 1>&2
                  continue
                fi

                if [ -d /proc/$CORE_PID ]; then
                  # process exists
                  break
                fi

                echo "[Setup] Core PID is $CORE_PID, but it was not found under /proc; perhaps it was killed or there is a problem with shareProcessNamespace" 1>&2
                return 2
              done
              echo "[Setup] Core PID is $CORE_PID" 1>&2

              return 0
            }

            REQUIRED_MEMLOCK_BYTES=8589934592 # 8GB
            function get_memlock_limit() {
              cat /proc/self/limits | grep -F 'Max locked memory' | awk '{print $4}'
            }

            function needs_memlock_setup() {
              # Expected: 'unlimited' or a number in bytes.
              local CURRENT_MEMLOCK_VALUE=$(get_memlock_limit)

              if [ "$CURRENT_MEMLOCK_VALUE" = "unlimited" ]; then
                return 1
              fi
              if [ "$CURRENT_MEMLOCK_VALUE" -ge "$REQUIRED_MEMLOCK_BYTES" ]; then
                return 1
              fi

              # memlock setup is necessary
              return 0
            }

            function adjust_memlock() {
              local CORE_PID="$1"
              # Expected: 'unlimited' or a number in bytes.
              local CURRENT_MEMLOCK_VALUE=$(get_memlock_limit)
              echo "[Setup] current soft memlock limit: $CURRENT_MEMLOCK_VALUE" 1>&2

              if [ "$CURRENT_MEMLOCK_VALUE" = "unlimited" ]; then
                echo "[Setup] current memlock limit is 'unlimited'. No change needed." 1>&2
                return 0
              fi

              if [ "$CURRENT_MEMLOCK_VALUE" -ge "$REQUIRED_MEMLOCK_BYTES" ]; then
                echo "[Setup] current memlock limit ($CURRENT_MEMLOCK_VALUE bytes) is already sufficient (>= 8GB). No change needed." 1>&2
                return 0
              fi

              echo "[Setup] current limit ($CURRENT_MEMLOCK_VALUE bytes) is below required 8GB, setting a higher limit" 1>&2

              if prlimit --pid $CORE_PID --memlock=$REQUIRED_MEMLOCK_BYTES:$REQUIRED_MEMLOCK_BYTES; then
                echo "[Setup] successfully set memlock limit for PID $CORE_PID" 1>&2
                return 0
              fi

              echo "[Setup] failed to set memlock prlimit. Check capabilities or node configuration." 1>&2
              return 1
            }

            if ! needs_memlock_setup; then
              echo "[Setup] memlock setup not required, will be idle" 1>&2
              exec tail -f /dev/null
            fi

            DELAY=0.2
            while true; do
              wait_for_core_pid $DELAY
              adjust_memlock $CORE_PID

              # wait for PID file to disappear; it is deleted by the Core container once Core starts running, or exits
              echo "[Setup] waiting for PID file to be deleted" 1>&2
              while [ -f "$PID_FILE" ]; do
                sleep 0.2
              done
              # wait a bit longer after initial setup
              DELAY=1
            done
          volumeMounts:
            - name: firebolt-core-data{{ if .Values.nonRoot }}-nr{{ end }}
              mountPath: /firebolt-core/volume
        {{- end }}
      volumes:
        - name: nodes-config
          configMap:
            name: {{ include "fbcore.fullname" . }}-nodes-config
            items:
              - key: config.json
                path: config.json
  volumeClaimTemplates:
    - metadata:
        name: firebolt-core-data{{ if .Values.nonRoot }}-nr{{ end }}
      spec:
        {{- toYaml $.Values.deployment.storageSpec | nindent 8 }}
